version: '3.8'
services:
  SHINtube:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      DB_URL: LTIdb
      DB_NAME: SHINtube
      DB_USER: #LTIdb-MONGO_INITDB_ROOT_USERNAME
      DB_PASS: #LTIdb-MONGO_INITDB_ROOT_PASSWORD
      MY_DOMAIN: #Deployment destination url
      BACK_DOMAIN: #url where video-api is installed
      REG_KEY: #Secret key for dynamic registration
    depends_on:
      - "LTIdb"
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"
  
  LTIdb:
    image: mongo
    volumes:
      - ./LTIdb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: #LTIdb-MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: #LTIdb-MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: auth
      